# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _m2cd2ea3140437a6e84b87f64e5b5d405
else:
    import _m2cd2ea3140437a6e84b87f64e5b5d405

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _m2cd2ea3140437a6e84b87f64e5b5d405.delete_SwigPyIterator

    def value(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator_equal(self, x)

    def copy(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator_copy(self)

    def next(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator_next(self)

    def __next__(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator___next__(self)

    def previous(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator_previous(self)

    def advance(self, n):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _m2cd2ea3140437a6e84b87f64e5b5d405:
_m2cd2ea3140437a6e84b87f64e5b5d405.SwigPyIterator_swigregister(SwigPyIterator)

class string(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def length(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_length(self)

    def max_size(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_max_size(self)

    def capacity(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_capacity(self)

    def reserve(self, __res_arg=0):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_reserve(self, __res_arg)

    def copy(self, __s, __n, __pos=0):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_copy(self, __s, __n, __pos)

    def c_str(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_c_str(self)

    def find(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_find(self, *args)

    def rfind(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_rfind(self, *args)

    def find_first_of(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_find_first_of(self, *args)

    def find_last_of(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_find_last_of(self, *args)

    def find_first_not_of(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_find_first_not_of(self, *args)

    def find_last_not_of(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_find_last_not_of(self, *args)

    def substr(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_substr(self, *args)

    def empty(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_empty(self)

    def size(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_size(self)

    def swap(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_swap(self, v)

    def begin(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_begin(self)

    def end(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_end(self)

    def rbegin(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_rbegin(self)

    def rend(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_rend(self)

    def get_allocator(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_get_allocator(self)

    def erase(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_erase(self, *args)

    def __init__(self, *args):
        _m2cd2ea3140437a6e84b87f64e5b5d405.string_swiginit(self, _m2cd2ea3140437a6e84b87f64e5b5d405.new_string(*args))

    def assign(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_assign(self, *args)

    def resize(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_resize(self, *args)

    def iterator(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___nonzero__(self)

    def __bool__(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___bool__(self)

    def __len__(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___len__(self)

    def __getslice__(self, i, j):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___delitem__(self, *args)

    def __getitem__(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___getitem__(self, *args)

    def __setitem__(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___setitem__(self, *args)

    def insert(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_insert(self, *args)

    def replace(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string_replace(self, *args)

    def __iadd__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___iadd__(self, v)

    def __add__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___add__(self, v)

    def __radd__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___radd__(self, v)

    def __str__(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___str__(self)

    def __rlshift__(self, out):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___rlshift__(self, out)

    def __eq__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___eq__(self, v)

    def __ne__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___ne__(self, v)

    def __gt__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___gt__(self, v)

    def __lt__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___lt__(self, v)

    def __ge__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___ge__(self, v)

    def __le__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.string___le__(self, v)
    __swig_destroy__ = _m2cd2ea3140437a6e84b87f64e5b5d405.delete_string

# Register string in _m2cd2ea3140437a6e84b87f64e5b5d405:
_m2cd2ea3140437a6e84b87f64e5b5d405.string_swigregister(string)
cvar = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar
string.npos = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.string_npos

class ios_base(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    erase_event = _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_erase_event
    imbue_event = _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_imbue_event
    copyfmt_event = _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_copyfmt_event

    def register_callback(self, __fn, __index):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_register_callback(self, __fn, __index)

    def flags(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_flags(self, *args)

    def setf(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_setf(self, *args)

    def unsetf(self, __mask):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_unsetf(self, __mask)

    def precision(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_precision(self, *args)

    def width(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_width(self, *args)

    @staticmethod
    def sync_with_stdio(__sync=True):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_sync_with_stdio(__sync)

    def imbue(self, __loc):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_imbue(self, __loc)

    def getloc(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_getloc(self)

    @staticmethod
    def xalloc():
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_xalloc()

    def iword(self, __ix):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_iword(self, __ix)

    def pword(self, __ix):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_pword(self, __ix)
    __swig_destroy__ = _m2cd2ea3140437a6e84b87f64e5b5d405.delete_ios_base

# Register ios_base in _m2cd2ea3140437a6e84b87f64e5b5d405:
_m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_swigregister(ios_base)
ios_base.boolalpha = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_boolalpha
ios_base.dec = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_dec
ios_base.fixed = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_fixed
ios_base.hex = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_hex
ios_base.internal = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_internal
ios_base.left = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_left
ios_base.oct = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_oct
ios_base.right = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_right
ios_base.scientific = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_scientific
ios_base.showbase = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_showbase
ios_base.showpoint = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_showpoint
ios_base.showpos = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_showpos
ios_base.skipws = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_skipws
ios_base.unitbuf = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_unitbuf
ios_base.uppercase = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_uppercase
ios_base.adjustfield = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_adjustfield
ios_base.basefield = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_basefield
ios_base.floatfield = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_floatfield
ios_base.badbit = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_badbit
ios_base.eofbit = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_eofbit
ios_base.failbit = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_failbit
ios_base.goodbit = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_goodbit
ios_base.app = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_app
ios_base.ate = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_ate
ios_base.binary = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_binary
ios_base.ios_base_in = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_ios_base_in
ios_base.out = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_out
ios_base.trunc = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_trunc
ios_base.beg = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_beg
ios_base.cur = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_cur
ios_base.end = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.ios_base_end

def ios_base_sync_with_stdio(__sync=True):
    return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_sync_with_stdio(__sync)

def ios_base_xalloc():
    return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_base_xalloc()

class ios(ios_base):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def rdstate(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_rdstate(self)

    def clear(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_clear(self, *args)

    def setstate(self, __state):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_setstate(self, __state)

    def good(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_good(self)

    def eof(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_eof(self)

    def fail(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_fail(self)

    def bad(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_bad(self)

    def exceptions(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_exceptions(self, *args)

    def __init__(self, __sb):
        _m2cd2ea3140437a6e84b87f64e5b5d405.ios_swiginit(self, _m2cd2ea3140437a6e84b87f64e5b5d405.new_ios(__sb))
    __swig_destroy__ = _m2cd2ea3140437a6e84b87f64e5b5d405.delete_ios

    def tie(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_tie(self, *args)

    def rdbuf(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_rdbuf(self, *args)

    def copyfmt(self, __rhs):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_copyfmt(self, __rhs)

    def fill(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_fill(self, *args)

    def imbue(self, __loc):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_imbue(self, __loc)

    def narrow(self, __c, __dfault):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_narrow(self, __c, __dfault)

    def widen(self, __c):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ios_widen(self, __c)

# Register ios in _m2cd2ea3140437a6e84b87f64e5b5d405:
_m2cd2ea3140437a6e84b87f64e5b5d405.ios_swigregister(ios)

class streambuf(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _m2cd2ea3140437a6e84b87f64e5b5d405.delete_streambuf

    def pubimbue(self, __loc):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_pubimbue(self, __loc)

    def getloc(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_getloc(self)

    def pubsetbuf(self, __s, __n):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_pubsetbuf(self, __s, __n)

    def pubseekoff(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_pubseekoff(self, *args)

    def pubseekpos(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_pubseekpos(self, *args)

    def pubsync(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_pubsync(self)

    def in_avail(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_in_avail(self)

    def snextc(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_snextc(self)

    def sbumpc(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_sbumpc(self)

    def sgetc(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_sgetc(self)

    def sgetn(self, __s, __n):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_sgetn(self, __s, __n)

    def sputbackc(self, __c):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_sputbackc(self, __c)

    def sungetc(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_sungetc(self)

    def sputc(self, __c):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_sputc(self, __c)

    def sputn(self, __s, __n):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_sputn(self, __s, __n)

# Register streambuf in _m2cd2ea3140437a6e84b87f64e5b5d405:
_m2cd2ea3140437a6e84b87f64e5b5d405.streambuf_swigregister(streambuf)

class ostream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _m2cd2ea3140437a6e84b87f64e5b5d405.ostream_swiginit(self, _m2cd2ea3140437a6e84b87f64e5b5d405.new_ostream(__sb))
    __swig_destroy__ = _m2cd2ea3140437a6e84b87f64e5b5d405.delete_ostream

    def __lshift__(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ostream___lshift__(self, *args)

    def put(self, __c):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ostream_put(self, __c)

    def write(self, __s, __n):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ostream_write(self, __s, __n)

    def flush(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ostream_flush(self)

    def tellp(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ostream_tellp(self)

    def seekp(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ostream_seekp(self, *args)

# Register ostream in _m2cd2ea3140437a6e84b87f64e5b5d405:
_m2cd2ea3140437a6e84b87f64e5b5d405.ostream_swigregister(ostream)
cin = cvar.cin
cout = cvar.cout
cerr = cvar.cerr
clog = cvar.clog

class istream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _m2cd2ea3140437a6e84b87f64e5b5d405.istream_swiginit(self, _m2cd2ea3140437a6e84b87f64e5b5d405.new_istream(__sb))
    __swig_destroy__ = _m2cd2ea3140437a6e84b87f64e5b5d405.delete_istream

    def __rshift__(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istream___rshift__(self, *args)

    def gcount(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istream_gcount(self)

    def get(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istream_get(self, *args)

    def getline(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istream_getline(self, *args)

    def ignore(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istream_ignore(self, *args)

    def peek(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istream_peek(self)

    def read(self, __s, __n):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istream_read(self, __s, __n)

    def readsome(self, __s, __n):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istream_readsome(self, __s, __n)

    def putback(self, __c):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istream_putback(self, __c)

    def unget(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istream_unget(self)

    def sync(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istream_sync(self)

    def tellg(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istream_tellg(self)

    def seekg(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istream_seekg(self, *args)

# Register istream in _m2cd2ea3140437a6e84b87f64e5b5d405:
_m2cd2ea3140437a6e84b87f64e5b5d405.istream_swigregister(istream)

class iostream(istream, ostream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _m2cd2ea3140437a6e84b87f64e5b5d405.iostream_swiginit(self, _m2cd2ea3140437a6e84b87f64e5b5d405.new_iostream(__sb))
    __swig_destroy__ = _m2cd2ea3140437a6e84b87f64e5b5d405.delete_iostream

# Register iostream in _m2cd2ea3140437a6e84b87f64e5b5d405:
_m2cd2ea3140437a6e84b87f64e5b5d405.iostream_swigregister(iostream)

endl_cb_ptr = _m2cd2ea3140437a6e84b87f64e5b5d405.endl_cb_ptr
endl = _m2cd2ea3140437a6e84b87f64e5b5d405.endl
ends_cb_ptr = _m2cd2ea3140437a6e84b87f64e5b5d405.ends_cb_ptr
ends = _m2cd2ea3140437a6e84b87f64e5b5d405.ends
flush_cb_ptr = _m2cd2ea3140437a6e84b87f64e5b5d405.flush_cb_ptr
flush = _m2cd2ea3140437a6e84b87f64e5b5d405.flush
class istringstream(istream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _m2cd2ea3140437a6e84b87f64e5b5d405.istringstream_swiginit(self, _m2cd2ea3140437a6e84b87f64e5b5d405.new_istringstream(*args))
    __swig_destroy__ = _m2cd2ea3140437a6e84b87f64e5b5d405.delete_istringstream

    def rdbuf(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istringstream_rdbuf(self)

    def str(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.istringstream_str(self, *args)

# Register istringstream in _m2cd2ea3140437a6e84b87f64e5b5d405:
_m2cd2ea3140437a6e84b87f64e5b5d405.istringstream_swigregister(istringstream)

class ostringstream(ostream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _m2cd2ea3140437a6e84b87f64e5b5d405.ostringstream_swiginit(self, _m2cd2ea3140437a6e84b87f64e5b5d405.new_ostringstream(*args))
    __swig_destroy__ = _m2cd2ea3140437a6e84b87f64e5b5d405.delete_ostringstream

    def rdbuf(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ostringstream_rdbuf(self)

    def str(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.ostringstream_str(self)

# Register ostringstream in _m2cd2ea3140437a6e84b87f64e5b5d405:
_m2cd2ea3140437a6e84b87f64e5b5d405.ostringstream_swigregister(ostringstream)

class stringstream(iostream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _m2cd2ea3140437a6e84b87f64e5b5d405.stringstream_swiginit(self, _m2cd2ea3140437a6e84b87f64e5b5d405.new_stringstream(*args))
    __swig_destroy__ = _m2cd2ea3140437a6e84b87f64e5b5d405.delete_stringstream

    def rdbuf(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.stringstream_rdbuf(self)

    def str(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.stringstream_str(self, *args)

# Register stringstream in _m2cd2ea3140437a6e84b87f64e5b5d405:
_m2cd2ea3140437a6e84b87f64e5b5d405.stringstream_swigregister(stringstream)

SHARED_PTR_DISOWN = _m2cd2ea3140437a6e84b87f64e5b5d405.SHARED_PTR_DISOWN
class wstring(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def length(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_length(self)

    def max_size(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_max_size(self)

    def capacity(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_capacity(self)

    def reserve(self, __res_arg=0):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_reserve(self, __res_arg)

    def copy(self, __s, __n, __pos=0):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_copy(self, __s, __n, __pos)

    def c_str(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_c_str(self)

    def find(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_find(self, *args)

    def rfind(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_rfind(self, *args)

    def find_first_of(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_find_first_of(self, *args)

    def find_last_of(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_find_last_of(self, *args)

    def find_first_not_of(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_find_first_not_of(self, *args)

    def find_last_not_of(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_find_last_not_of(self, *args)

    def substr(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_substr(self, *args)

    def empty(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_empty(self)

    def size(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_size(self)

    def swap(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_swap(self, v)

    def begin(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_begin(self)

    def end(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_end(self)

    def rbegin(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_rbegin(self)

    def rend(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_rend(self)

    def get_allocator(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_get_allocator(self)

    def erase(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_erase(self, *args)

    def __init__(self, *args):
        _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_swiginit(self, _m2cd2ea3140437a6e84b87f64e5b5d405.new_wstring(*args))

    def assign(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_assign(self, *args)

    def resize(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_resize(self, *args)

    def iterator(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___nonzero__(self)

    def __bool__(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___bool__(self)

    def __len__(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___len__(self)

    def __getslice__(self, i, j):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___delitem__(self, *args)

    def __getitem__(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___getitem__(self, *args)

    def __setitem__(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___setitem__(self, *args)

    def insert(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_insert(self, *args)

    def replace(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring_replace(self, *args)

    def __iadd__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___iadd__(self, v)

    def __add__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___add__(self, v)

    def __radd__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___radd__(self, v)

    def __str__(self):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___str__(self)

    def __rlshift__(self, out):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___rlshift__(self, out)

    def __eq__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___eq__(self, v)

    def __ne__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___ne__(self, v)

    def __gt__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___gt__(self, v)

    def __lt__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___lt__(self, v)

    def __ge__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___ge__(self, v)

    def __le__(self, v):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.wstring___le__(self, v)
    __swig_destroy__ = _m2cd2ea3140437a6e84b87f64e5b5d405.delete_wstring

# Register wstring in _m2cd2ea3140437a6e84b87f64e5b5d405:
_m2cd2ea3140437a6e84b87f64e5b5d405.wstring_swigregister(wstring)
wstring.npos = _m2cd2ea3140437a6e84b87f64e5b5d405.cvar.wstring_npos


def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    all_keys = [attr for attr in dir(class_type) if not attr.startswith('__')and attr != '_s' ]
    data_keys = sorted(class_type.__swig_setmethods__.keys())
    method_keys = [ x for x in all_keys if x not in data_keys ]
    raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
     (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
# this line is changed to handle older swigs that used PySwigObject instead of the current SwigPyObject
        if type(value).__name__ == 'SwigPyObject' or type(value).__name__ == 'PySwigObject' :
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        all_keys = [attr for attr in dir(class_type) if not attr.startswith('__') and attr != '_s' ]
        data_keys = sorted(class_type.__swig_setmethods__.keys())
        method_keys = [ x for x in all_keys if x not in data_keys ]
        raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
         (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,1)

class BLDC_MOTOR(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __getitem__(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR___getitem__(self, *args)

    def __len__(self, *args):
        return _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR___len__(self, *args)
    init_voltage = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_init_voltage_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_init_voltage_set)
    init_current = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_init_current_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_init_current_set)
    init_omega = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_init_omega_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_init_omega_set)
    init_angle = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_init_angle_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_init_angle_set)
    init_tau_load = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_init_tau_load_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_init_tau_load_set)
    R = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_R_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_R_set)
    L = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_L_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_L_set)
    Ke = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_Ke_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_Ke_set)
    Kt = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_Kt_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_Kt_set)
    J = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_J_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_J_set)
    B = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_B_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_B_set)
    current = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_current_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_current_set)
    omega = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_omega_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_omega_set)
    theta = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_theta_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_theta_set)
    torque = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_torque_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_torque_set)
    back_emf = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_back_emf_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_back_emf_set)
    voltage = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_voltage_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_voltage_set)
    tau_load = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_tau_load_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_tau_load_set)
    power = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_power_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_power_set)
    rpm = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_rpm_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_rpm_set)
    time = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_time_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_time_set)
    stall = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_stall_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_stall_set)
    stallTime = property(_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_stallTime_get, _m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_stallTime_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2cd2ea3140437a6e84b87f64e5b5d405.new_BLDC_MOTOR()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "BLDC_MOTOR", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW


    __swig_destroy__ = _m2cd2ea3140437a6e84b87f64e5b5d405.delete_BLDC_MOTOR

# Register BLDC_MOTOR in _m2cd2ea3140437a6e84b87f64e5b5d405:
_m2cd2ea3140437a6e84b87f64e5b5d405.BLDC_MOTOR_swigregister(BLDC_MOTOR)


if 'BLDC_MOTOR' in globals():
    BLDC_MOTOR.__setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)


def bldc_motor_default_data(*args):
    return _m2cd2ea3140437a6e84b87f64e5b5d405.bldc_motor_default_data(*args)

def bldc_motor_init(*args):
    return _m2cd2ea3140437a6e84b87f64e5b5d405.bldc_motor_init(*args)

def bldc_motor_deriv(*args):
    return _m2cd2ea3140437a6e84b87f64e5b5d405.bldc_motor_deriv(*args)

def bldc_motor_integ(*args):
    return _m2cd2ea3140437a6e84b87f64e5b5d405.bldc_motor_integ(*args)

def bldc_motor_shutdown(*args):
    return _m2cd2ea3140437a6e84b87f64e5b5d405.bldc_motor_shutdown(*args)


