# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _ma9557597abdbd3daf7ecce6896a576f7
else:
    import _ma9557597abdbd3daf7ecce6896a576f7

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_SwigPyIterator

    def value(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator_equal(self, x)

    def copy(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator_copy(self)

    def next(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator_next(self)

    def __next__(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator___next__(self)

    def previous(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator_previous(self)

    def advance(self, n):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.SwigPyIterator_swigregister(SwigPyIterator)

class string(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def length(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_length(self)

    def max_size(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_max_size(self)

    def capacity(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_capacity(self)

    def reserve(self, __res_arg=0):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_reserve(self, __res_arg)

    def copy(self, __s, __n, __pos=0):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_copy(self, __s, __n, __pos)

    def c_str(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_c_str(self)

    def find(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_find(self, *args)

    def rfind(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_rfind(self, *args)

    def find_first_of(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_find_first_of(self, *args)

    def find_last_of(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_find_last_of(self, *args)

    def find_first_not_of(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_find_first_not_of(self, *args)

    def find_last_not_of(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_find_last_not_of(self, *args)

    def substr(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_substr(self, *args)

    def empty(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_empty(self)

    def size(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_size(self)

    def swap(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_swap(self, v)

    def begin(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_begin(self)

    def end(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_end(self)

    def rbegin(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_rbegin(self)

    def rend(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_rend(self)

    def get_allocator(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_get_allocator(self)

    def erase(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_erase(self, *args)

    def __init__(self, *args):
        _ma9557597abdbd3daf7ecce6896a576f7.string_swiginit(self, _ma9557597abdbd3daf7ecce6896a576f7.new_string(*args))

    def assign(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_assign(self, *args)

    def resize(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_resize(self, *args)

    def iterator(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___nonzero__(self)

    def __bool__(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___bool__(self)

    def __len__(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___len__(self)

    def __getslice__(self, i, j):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___setitem__(self, *args)

    def insert(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_insert(self, *args)

    def replace(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.string_replace(self, *args)

    def __iadd__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___iadd__(self, v)

    def __add__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___add__(self, v)

    def __radd__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___radd__(self, v)

    def __str__(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___str__(self)

    def __rlshift__(self, out):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___rlshift__(self, out)

    def __eq__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___eq__(self, v)

    def __ne__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___ne__(self, v)

    def __gt__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___gt__(self, v)

    def __lt__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___lt__(self, v)

    def __ge__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___ge__(self, v)

    def __le__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.string___le__(self, v)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_string

# Register string in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.string_swigregister(string)
cvar = _ma9557597abdbd3daf7ecce6896a576f7.cvar
string.npos = _ma9557597abdbd3daf7ecce6896a576f7.cvar.string_npos

class ios_base(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    erase_event = _ma9557597abdbd3daf7ecce6896a576f7.ios_base_erase_event
    imbue_event = _ma9557597abdbd3daf7ecce6896a576f7.ios_base_imbue_event
    copyfmt_event = _ma9557597abdbd3daf7ecce6896a576f7.ios_base_copyfmt_event

    def register_callback(self, __fn, __index):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_register_callback(self, __fn, __index)

    def flags(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_flags(self, *args)

    def setf(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_setf(self, *args)

    def unsetf(self, __mask):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_unsetf(self, __mask)

    def precision(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_precision(self, *args)

    def width(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_width(self, *args)

    @staticmethod
    def sync_with_stdio(__sync=True):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_sync_with_stdio(__sync)

    def imbue(self, __loc):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_imbue(self, __loc)

    def getloc(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_getloc(self)

    @staticmethod
    def xalloc():
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_xalloc()

    def iword(self, __ix):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_iword(self, __ix)

    def pword(self, __ix):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_pword(self, __ix)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_ios_base

# Register ios_base in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.ios_base_swigregister(ios_base)
ios_base.boolalpha = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_boolalpha
ios_base.dec = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_dec
ios_base.fixed = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_fixed
ios_base.hex = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_hex
ios_base.internal = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_internal
ios_base.left = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_left
ios_base.oct = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_oct
ios_base.right = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_right
ios_base.scientific = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_scientific
ios_base.showbase = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_showbase
ios_base.showpoint = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_showpoint
ios_base.showpos = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_showpos
ios_base.skipws = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_skipws
ios_base.unitbuf = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_unitbuf
ios_base.uppercase = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_uppercase
ios_base.adjustfield = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_adjustfield
ios_base.basefield = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_basefield
ios_base.floatfield = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_floatfield
ios_base.badbit = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_badbit
ios_base.eofbit = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_eofbit
ios_base.failbit = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_failbit
ios_base.goodbit = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_goodbit
ios_base.app = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_app
ios_base.ate = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_ate
ios_base.binary = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_binary
ios_base.ios_base_in = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_ios_base_in
ios_base.out = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_out
ios_base.trunc = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_trunc
ios_base.beg = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_beg
ios_base.cur = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_cur
ios_base.end = _ma9557597abdbd3daf7ecce6896a576f7.cvar.ios_base_end

def ios_base_sync_with_stdio(__sync=True):
    return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_sync_with_stdio(__sync)

def ios_base_xalloc():
    return _ma9557597abdbd3daf7ecce6896a576f7.ios_base_xalloc()

class ios(ios_base):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def rdstate(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_rdstate(self)

    def clear(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_clear(self, *args)

    def setstate(self, __state):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_setstate(self, __state)

    def good(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_good(self)

    def eof(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_eof(self)

    def fail(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_fail(self)

    def bad(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_bad(self)

    def exceptions(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_exceptions(self, *args)

    def __init__(self, __sb):
        _ma9557597abdbd3daf7ecce6896a576f7.ios_swiginit(self, _ma9557597abdbd3daf7ecce6896a576f7.new_ios(__sb))
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_ios

    def tie(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_tie(self, *args)

    def rdbuf(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_rdbuf(self, *args)

    def copyfmt(self, __rhs):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_copyfmt(self, __rhs)

    def fill(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_fill(self, *args)

    def imbue(self, __loc):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_imbue(self, __loc)

    def narrow(self, __c, __dfault):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_narrow(self, __c, __dfault)

    def widen(self, __c):
        return _ma9557597abdbd3daf7ecce6896a576f7.ios_widen(self, __c)

# Register ios in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.ios_swigregister(ios)

class streambuf(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_streambuf

    def pubimbue(self, __loc):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_pubimbue(self, __loc)

    def getloc(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_getloc(self)

    def pubsetbuf(self, __s, __n):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_pubsetbuf(self, __s, __n)

    def pubseekoff(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_pubseekoff(self, *args)

    def pubseekpos(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_pubseekpos(self, *args)

    def pubsync(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_pubsync(self)

    def in_avail(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_in_avail(self)

    def snextc(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_snextc(self)

    def sbumpc(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_sbumpc(self)

    def sgetc(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_sgetc(self)

    def sgetn(self, __s, __n):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_sgetn(self, __s, __n)

    def sputbackc(self, __c):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_sputbackc(self, __c)

    def sungetc(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_sungetc(self)

    def sputc(self, __c):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_sputc(self, __c)

    def sputn(self, __s, __n):
        return _ma9557597abdbd3daf7ecce6896a576f7.streambuf_sputn(self, __s, __n)

# Register streambuf in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.streambuf_swigregister(streambuf)

class ostream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _ma9557597abdbd3daf7ecce6896a576f7.ostream_swiginit(self, _ma9557597abdbd3daf7ecce6896a576f7.new_ostream(__sb))
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_ostream

    def __lshift__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ostream___lshift__(self, *args)

    def put(self, __c):
        return _ma9557597abdbd3daf7ecce6896a576f7.ostream_put(self, __c)

    def write(self, __s, __n):
        return _ma9557597abdbd3daf7ecce6896a576f7.ostream_write(self, __s, __n)

    def flush(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.ostream_flush(self)

    def tellp(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.ostream_tellp(self)

    def seekp(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ostream_seekp(self, *args)

# Register ostream in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.ostream_swigregister(ostream)
cin = cvar.cin
cout = cvar.cout
cerr = cvar.cerr
clog = cvar.clog

class istream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _ma9557597abdbd3daf7ecce6896a576f7.istream_swiginit(self, _ma9557597abdbd3daf7ecce6896a576f7.new_istream(__sb))
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_istream

    def __rshift__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.istream___rshift__(self, *args)

    def gcount(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.istream_gcount(self)

    def get(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.istream_get(self, *args)

    def getline(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.istream_getline(self, *args)

    def ignore(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.istream_ignore(self, *args)

    def peek(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.istream_peek(self)

    def read(self, __s, __n):
        return _ma9557597abdbd3daf7ecce6896a576f7.istream_read(self, __s, __n)

    def readsome(self, __s, __n):
        return _ma9557597abdbd3daf7ecce6896a576f7.istream_readsome(self, __s, __n)

    def putback(self, __c):
        return _ma9557597abdbd3daf7ecce6896a576f7.istream_putback(self, __c)

    def unget(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.istream_unget(self)

    def sync(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.istream_sync(self)

    def tellg(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.istream_tellg(self)

    def seekg(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.istream_seekg(self, *args)

# Register istream in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.istream_swigregister(istream)

class iostream(istream, ostream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _ma9557597abdbd3daf7ecce6896a576f7.iostream_swiginit(self, _ma9557597abdbd3daf7ecce6896a576f7.new_iostream(__sb))
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_iostream

# Register iostream in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.iostream_swigregister(iostream)

endl_cb_ptr = _ma9557597abdbd3daf7ecce6896a576f7.endl_cb_ptr
endl = _ma9557597abdbd3daf7ecce6896a576f7.endl
ends_cb_ptr = _ma9557597abdbd3daf7ecce6896a576f7.ends_cb_ptr
ends = _ma9557597abdbd3daf7ecce6896a576f7.ends
flush_cb_ptr = _ma9557597abdbd3daf7ecce6896a576f7.flush_cb_ptr
flush = _ma9557597abdbd3daf7ecce6896a576f7.flush
class istringstream(istream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _ma9557597abdbd3daf7ecce6896a576f7.istringstream_swiginit(self, _ma9557597abdbd3daf7ecce6896a576f7.new_istringstream(*args))
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_istringstream

    def rdbuf(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.istringstream_rdbuf(self)

    def str(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.istringstream_str(self, *args)

# Register istringstream in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.istringstream_swigregister(istringstream)

class ostringstream(ostream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _ma9557597abdbd3daf7ecce6896a576f7.ostringstream_swiginit(self, _ma9557597abdbd3daf7ecce6896a576f7.new_ostringstream(*args))
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_ostringstream

    def rdbuf(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.ostringstream_rdbuf(self)

    def str(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.ostringstream_str(self)

# Register ostringstream in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.ostringstream_swigregister(ostringstream)

class stringstream(iostream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _ma9557597abdbd3daf7ecce6896a576f7.stringstream_swiginit(self, _ma9557597abdbd3daf7ecce6896a576f7.new_stringstream(*args))
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_stringstream

    def rdbuf(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.stringstream_rdbuf(self)

    def str(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.stringstream_str(self, *args)

# Register stringstream in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.stringstream_swigregister(stringstream)

SHARED_PTR_DISOWN = _ma9557597abdbd3daf7ecce6896a576f7.SHARED_PTR_DISOWN
class wstring(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def length(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_length(self)

    def max_size(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_max_size(self)

    def capacity(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_capacity(self)

    def reserve(self, __res_arg=0):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_reserve(self, __res_arg)

    def copy(self, __s, __n, __pos=0):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_copy(self, __s, __n, __pos)

    def c_str(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_c_str(self)

    def find(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_find(self, *args)

    def rfind(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_rfind(self, *args)

    def find_first_of(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_find_first_of(self, *args)

    def find_last_of(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_find_last_of(self, *args)

    def find_first_not_of(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_find_first_not_of(self, *args)

    def find_last_not_of(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_find_last_not_of(self, *args)

    def substr(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_substr(self, *args)

    def empty(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_empty(self)

    def size(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_size(self)

    def swap(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_swap(self, v)

    def begin(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_begin(self)

    def end(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_end(self)

    def rbegin(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_rbegin(self)

    def rend(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_rend(self)

    def get_allocator(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_get_allocator(self)

    def erase(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_erase(self, *args)

    def __init__(self, *args):
        _ma9557597abdbd3daf7ecce6896a576f7.wstring_swiginit(self, _ma9557597abdbd3daf7ecce6896a576f7.new_wstring(*args))

    def assign(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_assign(self, *args)

    def resize(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_resize(self, *args)

    def iterator(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___nonzero__(self)

    def __bool__(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___bool__(self)

    def __len__(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___len__(self)

    def __getslice__(self, i, j):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___setitem__(self, *args)

    def insert(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_insert(self, *args)

    def replace(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring_replace(self, *args)

    def __iadd__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___iadd__(self, v)

    def __add__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___add__(self, v)

    def __radd__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___radd__(self, v)

    def __str__(self):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___str__(self)

    def __rlshift__(self, out):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___rlshift__(self, out)

    def __eq__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___eq__(self, v)

    def __ne__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___ne__(self, v)

    def __gt__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___gt__(self, v)

    def __lt__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___lt__(self, v)

    def __ge__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___ge__(self, v)

    def __le__(self, v):
        return _ma9557597abdbd3daf7ecce6896a576f7.wstring___le__(self, v)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_wstring

# Register wstring in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.wstring_swigregister(wstring)
wstring.npos = _ma9557597abdbd3daf7ecce6896a576f7.cvar.wstring_npos


def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    all_keys = [attr for attr in dir(class_type) if not attr.startswith('__')and attr != '_s' ]
    data_keys = sorted(class_type.__swig_setmethods__.keys())
    method_keys = [ x for x in all_keys if x not in data_keys ]
    raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
     (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
# this line is changed to handle older swigs that used PySwigObject instead of the current SwigPyObject
        if type(value).__name__ == 'SwigPyObject' or type(value).__name__ == 'PySwigObject' :
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        all_keys = [attr for attr in dir(class_type) if not attr.startswith('__') and attr != '_s' ]
        data_keys = sorted(class_type.__swig_setmethods__.keys())
        method_keys = [ x for x in all_keys if x not in data_keys ]
        raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
         (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,1)

import sim_services
import med004e9567e72749b6d50f5dbf2a207f
import m2cd2ea3140437a6e84b87f64e5b5d405
import mcc1eb08e3f94331d1812c71b9fae1372
class SimEnvironment(sim_services.Environment):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)


    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_SimEnvironment()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SimEnvironment", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.SimEnvironment___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.SimEnvironment___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_SimEnvironment

# Register SimEnvironment in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.SimEnvironment_swigregister(SimEnvironment)


def exec_collect_init(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.exec_collect_init(*args)
class SysSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    sched = property(_ma9557597abdbd3daf7ecce6896a576f7.SysSimObject_sched_get)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_SysSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SysSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.SysSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.SysSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.SysSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.SysSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_SysSimObject

# Register SysSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.SysSimObject_swigregister(SysSimObject)

class MonteCarloSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    mc = property(_ma9557597abdbd3daf7ecce6896a576f7.MonteCarloSimObject_mc_get, _ma9557597abdbd3daf7ecce6896a576f7.MonteCarloSimObject_mc_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_MonteCarloSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MonteCarloSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MonteCarloSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MonteCarloSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MonteCarloSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MonteCarloSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_MonteCarloSimObject

# Register MonteCarloSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.MonteCarloSimObject_swigregister(MonteCarloSimObject)

class MemoryManagerSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    mm = property(_ma9557597abdbd3daf7ecce6896a576f7.MemoryManagerSimObject_mm_get, _ma9557597abdbd3daf7ecce6896a576f7.MemoryManagerSimObject_mm_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_MemoryManagerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MemoryManagerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MemoryManagerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MemoryManagerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MemoryManagerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MemoryManagerSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_MemoryManagerSimObject

# Register MemoryManagerSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.MemoryManagerSimObject_swigregister(MemoryManagerSimObject)

class CheckPointRestartSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    cpr = property(_ma9557597abdbd3daf7ecce6896a576f7.CheckPointRestartSimObject_cpr_get, _ma9557597abdbd3daf7ecce6896a576f7.CheckPointRestartSimObject_cpr_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_CheckPointRestartSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "CheckPointRestartSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.CheckPointRestartSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.CheckPointRestartSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.CheckPointRestartSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.CheckPointRestartSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_CheckPointRestartSimObject

# Register CheckPointRestartSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.CheckPointRestartSimObject_swigregister(CheckPointRestartSimObject)

class SieSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    sie = property(_ma9557597abdbd3daf7ecce6896a576f7.SieSimObject_sie_get, _ma9557597abdbd3daf7ecce6896a576f7.SieSimObject_sie_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_SieSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SieSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.SieSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.SieSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.SieSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.SieSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_SieSimObject

# Register SieSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.SieSimObject_swigregister(SieSimObject)

class CommandLineArgumentsSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    cmd_args = property(_ma9557597abdbd3daf7ecce6896a576f7.CommandLineArgumentsSimObject_cmd_args_get, _ma9557597abdbd3daf7ecce6896a576f7.CommandLineArgumentsSimObject_cmd_args_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_CommandLineArgumentsSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "CommandLineArgumentsSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.CommandLineArgumentsSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.CommandLineArgumentsSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.CommandLineArgumentsSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.CommandLineArgumentsSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_CommandLineArgumentsSimObject

# Register CommandLineArgumentsSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.CommandLineArgumentsSimObject_swigregister(CommandLineArgumentsSimObject)

class MessageSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    mpublisher = property(_ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_mpublisher_get, _ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_mpublisher_set)
    mcout = property(_ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_mcout_get, _ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_mcout_set)
    mtcout = property(_ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_mtcout_get, _ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_mtcout_set)
    mfile = property(_ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_mfile_get)
    mdevice = property(_ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_mdevice_get, _ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_mdevice_set)
    pfile = property(_ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_pfile_get)
    message_file_manager = property(_ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_message_file_manager_get, _ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_message_file_manager_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_MessageSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MessageSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_call_function_double(self, *args)

    def separate_thread_set_enabled(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_separate_thread_set_enabled(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_MessageSimObject

# Register MessageSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.MessageSimObject_swigregister(MessageSimObject)

class JITSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    jit = property(_ma9557597abdbd3daf7ecce6896a576f7.JITSimObject_jit_get, _ma9557597abdbd3daf7ecce6896a576f7.JITSimObject_jit_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_JITSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "JITSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.JITSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.JITSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.JITSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.JITSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_JITSimObject

# Register JITSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.JITSimObject_swigregister(JITSimObject)

class InputProcessorSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    ip = property(_ma9557597abdbd3daf7ecce6896a576f7.InputProcessorSimObject_ip_get, _ma9557597abdbd3daf7ecce6896a576f7.InputProcessorSimObject_ip_set)
    mtv = property(_ma9557597abdbd3daf7ecce6896a576f7.InputProcessorSimObject_mtv_get, _ma9557597abdbd3daf7ecce6896a576f7.InputProcessorSimObject_mtv_set)
    units_map_ptr = property(_ma9557597abdbd3daf7ecce6896a576f7.InputProcessorSimObject_units_map_ptr_get, _ma9557597abdbd3daf7ecce6896a576f7.InputProcessorSimObject_units_map_ptr_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_InputProcessorSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InputProcessorSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW


    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_InputProcessorSimObject

    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InputProcessorSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InputProcessorSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InputProcessorSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InputProcessorSimObject___len__(self, *args)

# Register InputProcessorSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.InputProcessorSimObject_swigregister(InputProcessorSimObject)

class ThreadProcessEventSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    ep = property(_ma9557597abdbd3daf7ecce6896a576f7.ThreadProcessEventSimObject_ep_get, _ma9557597abdbd3daf7ecce6896a576f7.ThreadProcessEventSimObject_ep_set)

    def __init__(self, *args, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_ThreadProcessEventSimObject(*args)
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            this.own(0)
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "ThreadProcessEventSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ThreadProcessEventSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ThreadProcessEventSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ThreadProcessEventSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ThreadProcessEventSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_ThreadProcessEventSimObject

# Register ThreadProcessEventSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.ThreadProcessEventSimObject_swigregister(ThreadProcessEventSimObject)

class EventManagerSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    em = property(_ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject_em_get, _ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject_em_set)
    ep = property(_ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject_ep_get, _ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject_ep_set)
    thread_process_event_so = property(_ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject_thread_process_event_so_get, _ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject_thread_process_event_so_set)
    thread_process_event_so_names = property(_ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject_thread_process_event_so_names_get, _ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject_thread_process_event_so_names_set)

    def create_thread_process_event(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject_create_thread_process_event(self, *args)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_EventManagerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "EventManagerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW


    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_EventManagerSimObject

    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject___len__(self, *args)

# Register EventManagerSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.EventManagerSimObject_swigregister(EventManagerSimObject)

class VariableServerSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    vs = property(_ma9557597abdbd3daf7ecce6896a576f7.VariableServerSimObject_vs_get, _ma9557597abdbd3daf7ecce6896a576f7.VariableServerSimObject_vs_set)
    sim_control_panel = property(_ma9557597abdbd3daf7ecce6896a576f7.VariableServerSimObject_sim_control_panel_get)
    trick_view = property(_ma9557597abdbd3daf7ecce6896a576f7.VariableServerSimObject_trick_view_get)
    malfunctions_trick_view = property(_ma9557597abdbd3daf7ecce6896a576f7.VariableServerSimObject_malfunctions_trick_view_get)
    stripchart = property(_ma9557597abdbd3daf7ecce6896a576f7.VariableServerSimObject_stripchart_get)
    monte_monitor = property(_ma9557597abdbd3daf7ecce6896a576f7.VariableServerSimObject_monte_monitor_get)

    def monte_carlo_disable_all_apps(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.VariableServerSimObject_monte_carlo_disable_all_apps(self, *args)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_VariableServerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "VariableServerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.VariableServerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.VariableServerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.VariableServerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.VariableServerSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_VariableServerSimObject

# Register VariableServerSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.VariableServerSimObject_swigregister(VariableServerSimObject)

class DataRecordDispatcherSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    drd = property(_ma9557597abdbd3daf7ecce6896a576f7.DataRecordDispatcherSimObject_drd_get)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_DataRecordDispatcherSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "DataRecordDispatcherSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.DataRecordDispatcherSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.DataRecordDispatcherSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.DataRecordDispatcherSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.DataRecordDispatcherSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_DataRecordDispatcherSimObject

# Register DataRecordDispatcherSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.DataRecordDispatcherSimObject_swigregister(DataRecordDispatcherSimObject)

class RTSyncSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    gtod_clock = property(_ma9557597abdbd3daf7ecce6896a576f7.RTSyncSimObject_gtod_clock_get, _ma9557597abdbd3daf7ecce6896a576f7.RTSyncSimObject_gtod_clock_set)
    itimer = property(_ma9557597abdbd3daf7ecce6896a576f7.RTSyncSimObject_itimer_get, _ma9557597abdbd3daf7ecce6896a576f7.RTSyncSimObject_itimer_set)
    rt_sync = property(_ma9557597abdbd3daf7ecce6896a576f7.RTSyncSimObject_rt_sync_get, _ma9557597abdbd3daf7ecce6896a576f7.RTSyncSimObject_rt_sync_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_RTSyncSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "RTSyncSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.RTSyncSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.RTSyncSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.RTSyncSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.RTSyncSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_RTSyncSimObject

# Register RTSyncSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.RTSyncSimObject_swigregister(RTSyncSimObject)

class FrameLogSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    frame_log = property(_ma9557597abdbd3daf7ecce6896a576f7.FrameLogSimObject_frame_log_get)

    def __init__(self, *args, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_FrameLogSimObject(*args)
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            this.own(0)
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "FrameLogSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.FrameLogSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.FrameLogSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.FrameLogSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.FrameLogSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_FrameLogSimObject

# Register FrameLogSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.FrameLogSimObject_swigregister(FrameLogSimObject)

class MasterSlaveSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    master = property(_ma9557597abdbd3daf7ecce6896a576f7.MasterSlaveSimObject_master_get, _ma9557597abdbd3daf7ecce6896a576f7.MasterSlaveSimObject_master_set)
    slave = property(_ma9557597abdbd3daf7ecce6896a576f7.MasterSlaveSimObject_slave_get, _ma9557597abdbd3daf7ecce6896a576f7.MasterSlaveSimObject_slave_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_MasterSlaveSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MasterSlaveSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MasterSlaveSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MasterSlaveSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MasterSlaveSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MasterSlaveSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_MasterSlaveSimObject

# Register MasterSlaveSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.MasterSlaveSimObject_swigregister(MasterSlaveSimObject)

class InstrumentationSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    echo_jobs = property(_ma9557597abdbd3daf7ecce6896a576f7.InstrumentationSimObject_echo_jobs_get, _ma9557597abdbd3daf7ecce6896a576f7.InstrumentationSimObject_echo_jobs_set)
    debug_pause = property(_ma9557597abdbd3daf7ecce6896a576f7.InstrumentationSimObject_debug_pause_get, _ma9557597abdbd3daf7ecce6896a576f7.InstrumentationSimObject_debug_pause_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_InstrumentationSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InstrumentationSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InstrumentationSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InstrumentationSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InstrumentationSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InstrumentationSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_InstrumentationSimObject

# Register InstrumentationSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.InstrumentationSimObject_swigregister(InstrumentationSimObject)

class InjectorExecSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    rtie = property(_ma9557597abdbd3daf7ecce6896a576f7.InjectorExecSimObject_rtie_get, _ma9557597abdbd3daf7ecce6896a576f7.InjectorExecSimObject_rtie_set)

    def __init__(self, *args, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_InjectorExecSimObject(*args)
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            this.own(0)
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InjectorExecSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InjectorExecSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InjectorExecSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InjectorExecSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InjectorExecSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_InjectorExecSimObject

# Register InjectorExecSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.InjectorExecSimObject_swigregister(InjectorExecSimObject)

class InjectorSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    rtis = property(_ma9557597abdbd3daf7ecce6896a576f7.InjectorSimObject_rtis_get, _ma9557597abdbd3daf7ecce6896a576f7.InjectorSimObject_rtis_set)
    injector_executor_so = property(_ma9557597abdbd3daf7ecce6896a576f7.InjectorSimObject_injector_executor_so_get, _ma9557597abdbd3daf7ecce6896a576f7.InjectorSimObject_injector_executor_so_set)
    injector_executor_so_names = property(_ma9557597abdbd3daf7ecce6896a576f7.InjectorSimObject_injector_executor_so_names_get, _ma9557597abdbd3daf7ecce6896a576f7.InjectorSimObject_injector_executor_so_names_set)

    def create_injector_executors(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InjectorSimObject_create_injector_executors(self, *args)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_InjectorSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InjectorSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW


    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_InjectorSimObject

    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InjectorSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InjectorSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InjectorSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.InjectorSimObject___len__(self, *args)

# Register InjectorSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.InjectorSimObject_swigregister(InjectorSimObject)

class ZeroconfSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    zc = property(_ma9557597abdbd3daf7ecce6896a576f7.ZeroconfSimObject_zc_get, _ma9557597abdbd3daf7ecce6896a576f7.ZeroconfSimObject_zc_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_ZeroconfSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "ZeroconfSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ZeroconfSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ZeroconfSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ZeroconfSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.ZeroconfSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_ZeroconfSimObject

# Register ZeroconfSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.ZeroconfSimObject_swigregister(ZeroconfSimObject)

class UnitTestSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    unit_tests = property(_ma9557597abdbd3daf7ecce6896a576f7.UnitTestSimObject_unit_tests_get, _ma9557597abdbd3daf7ecce6896a576f7.UnitTestSimObject_unit_tests_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_UnitTestSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "UnitTestSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.UnitTestSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.UnitTestSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.UnitTestSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.UnitTestSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_UnitTestSimObject

# Register UnitTestSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.UnitTestSimObject_swigregister(UnitTestSimObject)

class UdUnitsSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    udunits = property(_ma9557597abdbd3daf7ecce6896a576f7.UdUnitsSimObject_udunits_get, _ma9557597abdbd3daf7ecce6896a576f7.UdUnitsSimObject_udunits_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_UdUnitsSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "UdUnitsSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.UdUnitsSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.UdUnitsSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.UdUnitsSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.UdUnitsSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_UdUnitsSimObject

# Register UdUnitsSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.UdUnitsSimObject_swigregister(UdUnitsSimObject)

class MyCivetServerSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    server = property(_ma9557597abdbd3daf7ecce6896a576f7.MyCivetServerSimObject_server_get, _ma9557597abdbd3daf7ecce6896a576f7.MyCivetServerSimObject_server_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_MyCivetServerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MyCivetServerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MyCivetServerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MyCivetServerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MyCivetServerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.MyCivetServerSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_MyCivetServerSimObject

# Register MyCivetServerSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.MyCivetServerSimObject_swigregister(MyCivetServerSimObject)

class BLDCSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    motor = property(_ma9557597abdbd3daf7ecce6896a576f7.BLDCSimObject_motor_get, _ma9557597abdbd3daf7ecce6896a576f7.BLDCSimObject_motor_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _ma9557597abdbd3daf7ecce6896a576f7.new_BLDCSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "BLDCSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.BLDCSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.BLDCSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.BLDCSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _ma9557597abdbd3daf7ecce6896a576f7.BLDCSimObject___len__(self, *args)
    __swig_destroy__ = _ma9557597abdbd3daf7ecce6896a576f7.delete_BLDCSimObject

# Register BLDCSimObject in _ma9557597abdbd3daf7ecce6896a576f7:
_ma9557597abdbd3daf7ecce6896a576f7.BLDCSimObject_swigregister(BLDCSimObject)


def castAsSimEnvironment(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsSimEnvironment(*args)

def castAsSysSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsSysSimObject(*args)

def castAsMonteCarloSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsMonteCarloSimObject(*args)

def castAsMemoryManagerSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsMemoryManagerSimObject(*args)

def castAsCheckPointRestartSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsCheckPointRestartSimObject(*args)

def castAsSieSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsSieSimObject(*args)

def castAsCommandLineArgumentsSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsCommandLineArgumentsSimObject(*args)

def castAsMessageSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsMessageSimObject(*args)

def castAsJITSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsJITSimObject(*args)

def castAsInputProcessorSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsInputProcessorSimObject(*args)

def castAsThreadProcessEventSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsThreadProcessEventSimObject(*args)

def castAsEventManagerSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsEventManagerSimObject(*args)

def castAsVariableServerSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsVariableServerSimObject(*args)

def castAsDataRecordDispatcherSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsDataRecordDispatcherSimObject(*args)

def castAsRTSyncSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsRTSyncSimObject(*args)

def castAsFrameLogSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsFrameLogSimObject(*args)

def castAsMasterSlaveSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsMasterSlaveSimObject(*args)

def castAsInstrumentationSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsInstrumentationSimObject(*args)

def castAsInjectorExecSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsInjectorExecSimObject(*args)

def castAsInjectorSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsInjectorSimObject(*args)

def castAsZeroconfSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsZeroconfSimObject(*args)

def castAsUnitTestSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsUnitTestSimObject(*args)

def castAsUdUnitsSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsUdUnitsSimObject(*args)

def castAsMyCivetServerSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsMyCivetServerSimObject(*args)

def castAsBLDCSimObject(*args):
    return _ma9557597abdbd3daf7ecce6896a576f7.castAsBLDCSimObject(*args)


