# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _med004e9567e72749b6d50f5dbf2a207f
else:
    import _med004e9567e72749b6d50f5dbf2a207f

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _med004e9567e72749b6d50f5dbf2a207f.delete_SwigPyIterator

    def value(self):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator_equal(self, x)

    def copy(self):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator_copy(self)

    def next(self):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator_next(self)

    def __next__(self):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator___next__(self)

    def previous(self):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator_previous(self)

    def advance(self, n):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _med004e9567e72749b6d50f5dbf2a207f:
_med004e9567e72749b6d50f5dbf2a207f.SwigPyIterator_swigregister(SwigPyIterator)

class string(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def length(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string_length(self)

    def max_size(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string_max_size(self)

    def capacity(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string_capacity(self)

    def reserve(self, __res_arg=0):
        return _med004e9567e72749b6d50f5dbf2a207f.string_reserve(self, __res_arg)

    def copy(self, __s, __n, __pos=0):
        return _med004e9567e72749b6d50f5dbf2a207f.string_copy(self, __s, __n, __pos)

    def c_str(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string_c_str(self)

    def find(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string_find(self, *args)

    def rfind(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string_rfind(self, *args)

    def find_first_of(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string_find_first_of(self, *args)

    def find_last_of(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string_find_last_of(self, *args)

    def find_first_not_of(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string_find_first_not_of(self, *args)

    def find_last_not_of(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string_find_last_not_of(self, *args)

    def substr(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string_substr(self, *args)

    def empty(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string_empty(self)

    def size(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string_size(self)

    def swap(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.string_swap(self, v)

    def begin(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string_begin(self)

    def end(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string_end(self)

    def rbegin(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string_rbegin(self)

    def rend(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string_rend(self)

    def get_allocator(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string_get_allocator(self)

    def erase(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string_erase(self, *args)

    def __init__(self, *args):
        _med004e9567e72749b6d50f5dbf2a207f.string_swiginit(self, _med004e9567e72749b6d50f5dbf2a207f.new_string(*args))

    def assign(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string_assign(self, *args)

    def resize(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string_resize(self, *args)

    def iterator(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string___nonzero__(self)

    def __bool__(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string___bool__(self)

    def __len__(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string___len__(self)

    def __getslice__(self, i, j):
        return _med004e9567e72749b6d50f5dbf2a207f.string___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _med004e9567e72749b6d50f5dbf2a207f.string___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string___delitem__(self, *args)

    def __getitem__(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string___getitem__(self, *args)

    def __setitem__(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string___setitem__(self, *args)

    def insert(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string_insert(self, *args)

    def replace(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.string_replace(self, *args)

    def __iadd__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.string___iadd__(self, v)

    def __add__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.string___add__(self, v)

    def __radd__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.string___radd__(self, v)

    def __str__(self):
        return _med004e9567e72749b6d50f5dbf2a207f.string___str__(self)

    def __rlshift__(self, out):
        return _med004e9567e72749b6d50f5dbf2a207f.string___rlshift__(self, out)

    def __eq__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.string___eq__(self, v)

    def __ne__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.string___ne__(self, v)

    def __gt__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.string___gt__(self, v)

    def __lt__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.string___lt__(self, v)

    def __ge__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.string___ge__(self, v)

    def __le__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.string___le__(self, v)
    __swig_destroy__ = _med004e9567e72749b6d50f5dbf2a207f.delete_string

# Register string in _med004e9567e72749b6d50f5dbf2a207f:
_med004e9567e72749b6d50f5dbf2a207f.string_swigregister(string)
cvar = _med004e9567e72749b6d50f5dbf2a207f.cvar
string.npos = _med004e9567e72749b6d50f5dbf2a207f.cvar.string_npos

class ios_base(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    erase_event = _med004e9567e72749b6d50f5dbf2a207f.ios_base_erase_event
    imbue_event = _med004e9567e72749b6d50f5dbf2a207f.ios_base_imbue_event
    copyfmt_event = _med004e9567e72749b6d50f5dbf2a207f.ios_base_copyfmt_event

    def register_callback(self, __fn, __index):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_base_register_callback(self, __fn, __index)

    def flags(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_base_flags(self, *args)

    def setf(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_base_setf(self, *args)

    def unsetf(self, __mask):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_base_unsetf(self, __mask)

    def precision(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_base_precision(self, *args)

    def width(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_base_width(self, *args)

    @staticmethod
    def sync_with_stdio(__sync=True):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_base_sync_with_stdio(__sync)

    def imbue(self, __loc):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_base_imbue(self, __loc)

    def getloc(self):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_base_getloc(self)

    @staticmethod
    def xalloc():
        return _med004e9567e72749b6d50f5dbf2a207f.ios_base_xalloc()

    def iword(self, __ix):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_base_iword(self, __ix)

    def pword(self, __ix):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_base_pword(self, __ix)
    __swig_destroy__ = _med004e9567e72749b6d50f5dbf2a207f.delete_ios_base

# Register ios_base in _med004e9567e72749b6d50f5dbf2a207f:
_med004e9567e72749b6d50f5dbf2a207f.ios_base_swigregister(ios_base)
ios_base.boolalpha = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_boolalpha
ios_base.dec = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_dec
ios_base.fixed = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_fixed
ios_base.hex = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_hex
ios_base.internal = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_internal
ios_base.left = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_left
ios_base.oct = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_oct
ios_base.right = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_right
ios_base.scientific = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_scientific
ios_base.showbase = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_showbase
ios_base.showpoint = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_showpoint
ios_base.showpos = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_showpos
ios_base.skipws = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_skipws
ios_base.unitbuf = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_unitbuf
ios_base.uppercase = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_uppercase
ios_base.adjustfield = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_adjustfield
ios_base.basefield = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_basefield
ios_base.floatfield = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_floatfield
ios_base.badbit = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_badbit
ios_base.eofbit = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_eofbit
ios_base.failbit = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_failbit
ios_base.goodbit = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_goodbit
ios_base.app = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_app
ios_base.ate = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_ate
ios_base.binary = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_binary
ios_base.ios_base_in = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_ios_base_in
ios_base.out = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_out
ios_base.trunc = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_trunc
ios_base.beg = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_beg
ios_base.cur = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_cur
ios_base.end = _med004e9567e72749b6d50f5dbf2a207f.cvar.ios_base_end

def ios_base_sync_with_stdio(__sync=True):
    return _med004e9567e72749b6d50f5dbf2a207f.ios_base_sync_with_stdio(__sync)

def ios_base_xalloc():
    return _med004e9567e72749b6d50f5dbf2a207f.ios_base_xalloc()

class ios(ios_base):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def rdstate(self):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_rdstate(self)

    def clear(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_clear(self, *args)

    def setstate(self, __state):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_setstate(self, __state)

    def good(self):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_good(self)

    def eof(self):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_eof(self)

    def fail(self):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_fail(self)

    def bad(self):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_bad(self)

    def exceptions(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_exceptions(self, *args)

    def __init__(self, __sb):
        _med004e9567e72749b6d50f5dbf2a207f.ios_swiginit(self, _med004e9567e72749b6d50f5dbf2a207f.new_ios(__sb))
    __swig_destroy__ = _med004e9567e72749b6d50f5dbf2a207f.delete_ios

    def tie(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_tie(self, *args)

    def rdbuf(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_rdbuf(self, *args)

    def copyfmt(self, __rhs):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_copyfmt(self, __rhs)

    def fill(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_fill(self, *args)

    def imbue(self, __loc):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_imbue(self, __loc)

    def narrow(self, __c, __dfault):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_narrow(self, __c, __dfault)

    def widen(self, __c):
        return _med004e9567e72749b6d50f5dbf2a207f.ios_widen(self, __c)

# Register ios in _med004e9567e72749b6d50f5dbf2a207f:
_med004e9567e72749b6d50f5dbf2a207f.ios_swigregister(ios)

class streambuf(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _med004e9567e72749b6d50f5dbf2a207f.delete_streambuf

    def pubimbue(self, __loc):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_pubimbue(self, __loc)

    def getloc(self):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_getloc(self)

    def pubsetbuf(self, __s, __n):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_pubsetbuf(self, __s, __n)

    def pubseekoff(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_pubseekoff(self, *args)

    def pubseekpos(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_pubseekpos(self, *args)

    def pubsync(self):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_pubsync(self)

    def in_avail(self):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_in_avail(self)

    def snextc(self):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_snextc(self)

    def sbumpc(self):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_sbumpc(self)

    def sgetc(self):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_sgetc(self)

    def sgetn(self, __s, __n):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_sgetn(self, __s, __n)

    def sputbackc(self, __c):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_sputbackc(self, __c)

    def sungetc(self):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_sungetc(self)

    def sputc(self, __c):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_sputc(self, __c)

    def sputn(self, __s, __n):
        return _med004e9567e72749b6d50f5dbf2a207f.streambuf_sputn(self, __s, __n)

# Register streambuf in _med004e9567e72749b6d50f5dbf2a207f:
_med004e9567e72749b6d50f5dbf2a207f.streambuf_swigregister(streambuf)

class ostream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _med004e9567e72749b6d50f5dbf2a207f.ostream_swiginit(self, _med004e9567e72749b6d50f5dbf2a207f.new_ostream(__sb))
    __swig_destroy__ = _med004e9567e72749b6d50f5dbf2a207f.delete_ostream

    def __lshift__(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.ostream___lshift__(self, *args)

    def put(self, __c):
        return _med004e9567e72749b6d50f5dbf2a207f.ostream_put(self, __c)

    def write(self, __s, __n):
        return _med004e9567e72749b6d50f5dbf2a207f.ostream_write(self, __s, __n)

    def flush(self):
        return _med004e9567e72749b6d50f5dbf2a207f.ostream_flush(self)

    def tellp(self):
        return _med004e9567e72749b6d50f5dbf2a207f.ostream_tellp(self)

    def seekp(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.ostream_seekp(self, *args)

# Register ostream in _med004e9567e72749b6d50f5dbf2a207f:
_med004e9567e72749b6d50f5dbf2a207f.ostream_swigregister(ostream)
cin = cvar.cin
cout = cvar.cout
cerr = cvar.cerr
clog = cvar.clog

class istream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _med004e9567e72749b6d50f5dbf2a207f.istream_swiginit(self, _med004e9567e72749b6d50f5dbf2a207f.new_istream(__sb))
    __swig_destroy__ = _med004e9567e72749b6d50f5dbf2a207f.delete_istream

    def __rshift__(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.istream___rshift__(self, *args)

    def gcount(self):
        return _med004e9567e72749b6d50f5dbf2a207f.istream_gcount(self)

    def get(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.istream_get(self, *args)

    def getline(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.istream_getline(self, *args)

    def ignore(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.istream_ignore(self, *args)

    def peek(self):
        return _med004e9567e72749b6d50f5dbf2a207f.istream_peek(self)

    def read(self, __s, __n):
        return _med004e9567e72749b6d50f5dbf2a207f.istream_read(self, __s, __n)

    def readsome(self, __s, __n):
        return _med004e9567e72749b6d50f5dbf2a207f.istream_readsome(self, __s, __n)

    def putback(self, __c):
        return _med004e9567e72749b6d50f5dbf2a207f.istream_putback(self, __c)

    def unget(self):
        return _med004e9567e72749b6d50f5dbf2a207f.istream_unget(self)

    def sync(self):
        return _med004e9567e72749b6d50f5dbf2a207f.istream_sync(self)

    def tellg(self):
        return _med004e9567e72749b6d50f5dbf2a207f.istream_tellg(self)

    def seekg(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.istream_seekg(self, *args)

# Register istream in _med004e9567e72749b6d50f5dbf2a207f:
_med004e9567e72749b6d50f5dbf2a207f.istream_swigregister(istream)

class iostream(istream, ostream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _med004e9567e72749b6d50f5dbf2a207f.iostream_swiginit(self, _med004e9567e72749b6d50f5dbf2a207f.new_iostream(__sb))
    __swig_destroy__ = _med004e9567e72749b6d50f5dbf2a207f.delete_iostream

# Register iostream in _med004e9567e72749b6d50f5dbf2a207f:
_med004e9567e72749b6d50f5dbf2a207f.iostream_swigregister(iostream)

endl_cb_ptr = _med004e9567e72749b6d50f5dbf2a207f.endl_cb_ptr
endl = _med004e9567e72749b6d50f5dbf2a207f.endl
ends_cb_ptr = _med004e9567e72749b6d50f5dbf2a207f.ends_cb_ptr
ends = _med004e9567e72749b6d50f5dbf2a207f.ends
flush_cb_ptr = _med004e9567e72749b6d50f5dbf2a207f.flush_cb_ptr
flush = _med004e9567e72749b6d50f5dbf2a207f.flush
class istringstream(istream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _med004e9567e72749b6d50f5dbf2a207f.istringstream_swiginit(self, _med004e9567e72749b6d50f5dbf2a207f.new_istringstream(*args))
    __swig_destroy__ = _med004e9567e72749b6d50f5dbf2a207f.delete_istringstream

    def rdbuf(self):
        return _med004e9567e72749b6d50f5dbf2a207f.istringstream_rdbuf(self)

    def str(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.istringstream_str(self, *args)

# Register istringstream in _med004e9567e72749b6d50f5dbf2a207f:
_med004e9567e72749b6d50f5dbf2a207f.istringstream_swigregister(istringstream)

class ostringstream(ostream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _med004e9567e72749b6d50f5dbf2a207f.ostringstream_swiginit(self, _med004e9567e72749b6d50f5dbf2a207f.new_ostringstream(*args))
    __swig_destroy__ = _med004e9567e72749b6d50f5dbf2a207f.delete_ostringstream

    def rdbuf(self):
        return _med004e9567e72749b6d50f5dbf2a207f.ostringstream_rdbuf(self)

    def str(self):
        return _med004e9567e72749b6d50f5dbf2a207f.ostringstream_str(self)

# Register ostringstream in _med004e9567e72749b6d50f5dbf2a207f:
_med004e9567e72749b6d50f5dbf2a207f.ostringstream_swigregister(ostringstream)

class stringstream(iostream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _med004e9567e72749b6d50f5dbf2a207f.stringstream_swiginit(self, _med004e9567e72749b6d50f5dbf2a207f.new_stringstream(*args))
    __swig_destroy__ = _med004e9567e72749b6d50f5dbf2a207f.delete_stringstream

    def rdbuf(self):
        return _med004e9567e72749b6d50f5dbf2a207f.stringstream_rdbuf(self)

    def str(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.stringstream_str(self, *args)

# Register stringstream in _med004e9567e72749b6d50f5dbf2a207f:
_med004e9567e72749b6d50f5dbf2a207f.stringstream_swigregister(stringstream)

SHARED_PTR_DISOWN = _med004e9567e72749b6d50f5dbf2a207f.SHARED_PTR_DISOWN
class wstring(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def length(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_length(self)

    def max_size(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_max_size(self)

    def capacity(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_capacity(self)

    def reserve(self, __res_arg=0):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_reserve(self, __res_arg)

    def copy(self, __s, __n, __pos=0):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_copy(self, __s, __n, __pos)

    def c_str(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_c_str(self)

    def find(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_find(self, *args)

    def rfind(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_rfind(self, *args)

    def find_first_of(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_find_first_of(self, *args)

    def find_last_of(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_find_last_of(self, *args)

    def find_first_not_of(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_find_first_not_of(self, *args)

    def find_last_not_of(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_find_last_not_of(self, *args)

    def substr(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_substr(self, *args)

    def empty(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_empty(self)

    def size(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_size(self)

    def swap(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_swap(self, v)

    def begin(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_begin(self)

    def end(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_end(self)

    def rbegin(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_rbegin(self)

    def rend(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_rend(self)

    def get_allocator(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_get_allocator(self)

    def erase(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_erase(self, *args)

    def __init__(self, *args):
        _med004e9567e72749b6d50f5dbf2a207f.wstring_swiginit(self, _med004e9567e72749b6d50f5dbf2a207f.new_wstring(*args))

    def assign(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_assign(self, *args)

    def resize(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_resize(self, *args)

    def iterator(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___nonzero__(self)

    def __bool__(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___bool__(self)

    def __len__(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___len__(self)

    def __getslice__(self, i, j):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___delitem__(self, *args)

    def __getitem__(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___getitem__(self, *args)

    def __setitem__(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___setitem__(self, *args)

    def insert(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_insert(self, *args)

    def replace(self, *args):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring_replace(self, *args)

    def __iadd__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___iadd__(self, v)

    def __add__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___add__(self, v)

    def __radd__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___radd__(self, v)

    def __str__(self):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___str__(self)

    def __rlshift__(self, out):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___rlshift__(self, out)

    def __eq__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___eq__(self, v)

    def __ne__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___ne__(self, v)

    def __gt__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___gt__(self, v)

    def __lt__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___lt__(self, v)

    def __ge__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___ge__(self, v)

    def __le__(self, v):
        return _med004e9567e72749b6d50f5dbf2a207f.wstring___le__(self, v)
    __swig_destroy__ = _med004e9567e72749b6d50f5dbf2a207f.delete_wstring

# Register wstring in _med004e9567e72749b6d50f5dbf2a207f:
_med004e9567e72749b6d50f5dbf2a207f.wstring_swigregister(wstring)
wstring.npos = _med004e9567e72749b6d50f5dbf2a207f.cvar.wstring_npos


def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    all_keys = [attr for attr in dir(class_type) if not attr.startswith('__')and attr != '_s' ]
    data_keys = sorted(class_type.__swig_setmethods__.keys())
    method_keys = [ x for x in all_keys if x not in data_keys ]
    raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
     (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
# this line is changed to handle older swigs that used PySwigObject instead of the current SwigPyObject
        if type(value).__name__ == 'SwigPyObject' or type(value).__name__ == 'PySwigObject' :
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        all_keys = [attr for attr in dir(class_type) if not attr.startswith('__') and attr != '_s' ]
        data_keys = sorted(class_type.__swig_setmethods__.keys())
        method_keys = [ x for x in all_keys if x not in data_keys ]
        raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
         (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,1)

import m2cd2ea3140437a6e84b87f64e5b5d405


